### PR TITLE
Restored compatibility with older versions of simple-peer and alternative implementations

### PR DESCRIPTION
**Pull request by nazar-pc**
As per comment in upstream PR

### CODE REVIEW

**Comment by t-mullen** [comment]
How do we know which channel is the default channel? The datachannel events can fire in any order. An application may believe it's writing to the peer's default channel and that data will be read on the secondary datachannel.

```javascript
peer.write('123')
var dc = peer.createDataChannel('1')
dc.write('abc')
```

```javascript
peer.on('data', (data) => { 
  data // 'abc' 
}
peer.on('datachannel', (dc) => {
  dc.on('data', (data) => {
    data /// '123'
  }
})
```

If I write to the peer object, I expect the remote peer object to emit that data, not another DataChannel object.

**Comment by nazar-pc** [comment]
Here we don't talk about order of all data channels, only the first and the rest.

In most cases users will only have one data channel and with older versions of simple-peer or alternative implementations the name of the channel can be anything, so let's be ready for that.

Now in case when there are multiple data channels I believe it if fair to assume that `default` will fire earlier than others. Even if it possible to achieve wrong order, users can still use `negotiated: true` or other means to ensure `default` is the first one. I think it is a reasonable tradeoff comparing to requiring all alternative implementations to use `default` as simple-peer does.

**Comment by t-mullen** [comment]
If we're not using the label for correlation, let's do away with labeling the channel "default" and restore the old channelName option/generator.

I think we should fire the `datachannel` event for the first channel received, seeing as it's not any kind of special default channel now.

**Comment by nazar-pc** [comment]
I agree, but why should we bother to generate random ID if we can just call it `default`? It may even be useful for debugging and documentation purposes to have a predictable name.

**Comment by t-mullen** [comment]
Sure that's fine, the generation of the label isn't a breaking change, just removing the option is.

**Comment by nazar-pc** [comment]
Yes, we can restore it and give it a constant default value

**Comment by t-mullen** [comment]
I've had to modify the condition here slightly since `self._channels === [self]` since the first DataChannel object is the Peer.

It still works and from my testing, the order is actually preserved.

**Pull request merged**
